image: Visual Studio 2019

environment:
  nodejs_version: "11"

init:
  - ps: |
      Install-Product node $env:nodejs_version
      "//registry.npmjs.org/:_authToken=$env:npm_auth_token`n" | out-file "$env:userprofile\.npmrc" -Encoding ASCII

cache:
  - node_modules

install:
  - cmd: echo %APPVEYOR_REPO_TAG%
  - cmd: git checkout %APPVEYOR_REPO_BRANCH%
  - cmd: npm install --loglevel error

build: off

deploy_script:
  - ps: |
      if($env:APPVEYOR_REPO_TAG -eq "true")
      {
        npm run deploy
      }
      else
      {
        npm run deploy:next
      }
      
  - ps: Update-AppveyorBuild -Version "$(cat version.bak)"